import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import { BsSearch } from "react-icons/bs";

export default function Home() {
  const [city, setcity] = useState("");
  const [weather, setweather] = useState({});
  const [loading, setloading] = useState(false);
  const url = `https://api.openweathermap.org/data/2.5/weather?q=dubai&units=imperial&appid=${process.env.NEXT_PUBLIC_OW_API_KEY} `;

  const fetchWeather = (e) => {
    e.preventDefault();
    setloading(true);
    axios.get(url).then((res) => {
      setweather(res.data);
      console.log(res.data);
    });
    setcity("");
    setloading(false);
  };
  return (
    <div>
      <Head>
        <title>iljaw</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Overlay */}
      <div className="bg-black" />
      {/* Background image  */}
      <Image
        src="https://images.unsplash.com/photo-1601134467661-3d775b999c8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1075&q=80"
        layout='fill'
        objectFit="cover"
        alt="bgimg"
      />
      <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
        <form
        >
          <div>
            <input
              className='bg-transparent border-none text-white focus:outline-none text-2xl'
              type='text'
              placeholder='Search city'
            />
          </div>
          <button onClick={fetchWeather}>
            <BsSearch size={20} />
          </button>
        </form>
      </div>

    </div>
  );
}
